name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: '1.14.3'
          otp-version: '23.3.4.18'
      - name: Install dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile --warnings-as-errors
