import Config

# NOTE: this file contains some security keys/certs that are *not* secrets, and are only used for local development purposes.

host = System.get_env("HUBS_HOST") || "hubs.local"

{cors_proxy_host, assets_host, link_host} =
  if host == "hubs.local" do
    {"hubs-proxy.local", "hubs-assets.local", "hubs-link.local"}
  else
    {"cors-proxy.#{host}", "assets.#{host}", "link.#{host}"}
  end

# To run reticulum across a LAN for local testing, uncomment and change the line below to the LAN IP
# host = cors_proxy_host = "192.168.1.27"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :ret, RetWeb.Endpoint,
  url: [scheme: "https", host: host, port: 443],
  static_url: [scheme: "https", host: host, port: 443],
  http: [port: 4001, otp_app: :ret],
  https: [
    port: 4000,
    otp_app: :ret,
    cipher_suite: :strong,
    #keyfile: "#{File.cwd!()}/priv/dev-ssl.key",
    #certfile: "#{File.cwd!()}/priv/dev-ssl.cert"
    keyfile: "priv/cert/key.pem",
    certfile: "priv/cert/cert.pem",

  ],
  cors_proxy_url: [scheme: "https", host: cors_proxy_host, port: 443],
  assets_url: [scheme: "https", host: assets_host, port: 443],
  link_url: [scheme: "https", host: link_host, port: 443],
  imgproxy_url: [scheme: "http", host: host, port: 5000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  secret_key_base: System.get_env("SECRET_KEY_BASE") || "txlMOtlaY5x3crvOCko4uV5PM29ul3zGo1oBGNO3cDXx+7GHLKqt0gR9qzgThxb5",
  legacy_secret_key_base: System.get_env("LEGACY_SECRET_KEY_BASE") || "txlMOtlaY5x3crvOCko4uV5PM29ul3zGo1oBGNO3cDXx+7GHLKqt0gR9qzgThxb5",
  allowed_origins: System.get_env("ALLOWED_ORIGINS") || "*",
  allow_crawlers: true

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem

# The `http:` config above can be replaced with:

#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ret, RetWeb.Endpoint,
  # static_url: [scheme: "https", host: "assets-prod.reticulum.io", port: 443],
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/ret_web/views/.*(ex)$},
      ~r{lib/ret_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :ret, Ret.Repo,
  username: "postgres",
  password: "postgres",
  database: "ret_dev",
  template: "template0",
  pool_size: 10

config :ret, Ret.SessionLockRepo,
  username: "postgres",
  password: "postgres",
  database: "ret_dev",
  template: "template0",
  pool_size: 10

config :ret, RetWeb.Plugs.HeaderAuthorization,
  header_name: "x-ret-admin-access-key",
  header_value: System.get_env("RETICULUM_ADMIN_KEY") || "admin-only"

config :ret, Ret.SlackClient,
  client_id: "",
  client_secret: "",
  bot_token: ""

# Token is our randomly generated auth token to append to Slacks slash command
# As a query param "token"
config :ret, RetWeb.Api.V1.SlackController, token: ""

config :ret, Ret.DiscordClient,
  client_id: "",
  client_secret: "",
  bot_token: ""

config :ret, RetWeb.Api.V1.WhatsNewController, token: ""

config :ret, RetWeb.Plugs.DashboardHeaderAuthorization, dashboard_access_key: ""

# Allow any origin for API access in dev
config :cors_plug, origin: System.get_env("CORS_ORIGINS", "*") |> String.split(",")

config :ret,
  upload_encryption_key: System.get_env("UPLOAD_ENCRYPTION_KEY") || "a8dedeb57adafa7821027d546f016efef5a501bd",
  bot_access_key: ""

config :ret, Ret.PageOriginWarmer, insecure_ssl: true

config :ret, Ret.HttpUtils, insecure_ssl: true

config :ret, Ret.MediaResolver,
  giphy_api_key: nil,
  deviantart_client_id: nil,
  deviantart_client_secret: nil,
  imgur_mashape_api_key: nil,
  imgur_client_id: nil,
  youtube_api_key: nil,
  sketchfab_api_key: nil,
  ytdl_host: nil,
  photomnemonic_endpoint: nil

config :ret, Ret.Speelycaptor,
  speelycaptor_endpoint: nil

config :ret, Ret.Storage,
  host: "https://#{host}",
  storage_path: "storage/dev",
  ttl: 60 * 60 * 24

asset_hosts =
  "https://localhost:4000 https://localhost:8080 " <>
    "https://#{host}:4000 https://#{host}:8080 https://#{host}:3000 https://#{host}:8989 https://#{host}:9090 https://#{cors_proxy_host}:4000"

websocket_hosts =
  "https://localhost:4000 https://localhost:8080 wss://localhost:4000 " <>
    "https://#{host}:4000 https://#{host}:8080 wss://#{host}:4000 wss://#{host}:8080 wss://#{host}:8989 wss://#{host}:9090 " <>
    "wss://#{host}:4000 wss://#{host}:8080 https://#{host}:8080 https://hubs.local:8080 wss://hubs.local:8080"

pse_origin = ""

# TEMP: 'unsafe-inline' needed because append_csp has a bug that doesn't properly add script hashes
config :ret, RetWeb.Plugs.AddCSP,
  script_src: "'unsafe-inline' #{asset_hosts}",
  font_src: asset_hosts,
  style_src: asset_hosts,
  connect_src:
    "https://#{host}:8080 #{asset_hosts} #{websocket_hosts} #{pse_origin}",
  img_src: "#{asset_hosts} #{pse_origin}",
  media_src: "#{asset_hosts} #{pse_origin}",
  manifest_src: asset_hosts,
  frame_src: "#{pse_origin}",
  child_src: "#{pse_origin}",
  worker_src: "#{pse_origin}"

# SMTP Mailer configuration for Mailcow Postfix
smtp_server = System.get_env("SMTP_SERVER", "mail.tobias-weiss.org")
smtp_port = String.to_integer(System.get_env("SMTP_PORT", "587"))
smtp_username = System.get_env("SMTP_USERNAME", "")
smtp_password = System.get_env("SMTP_PASSWORD", "")

config :ret, Ret.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: smtp_server,
  port: smtp_port,
  username: smtp_username,
  password: smtp_password,
  tls: :always,
  ssl: false,
  auth: :always,
  allowed_tls_versions: [:"tlsv1.2"],
  no_mx_lookups: true,
  retries: 3

config :ret, RetWeb.Email, from: System.get_env("EMAIL_FROM", "hubs@tobias-weiss.org")

config :ret, Ret.OAuthToken, oauth_token_key: ""

config :ret, Ret.Guardian,
  issuer: "ret",
  secret_key: System.get_env("GUARDIAN_SECRET_KEY") || "47iqPEdWcfE7xRnyaxKDLt9OGEtkQG3SycHBEMOuT2qARmoESnhc76IgCUjaQIwX",
  ttl: {12, :weeks}

config :web_push_encryption, :vapid_details,
  subject: System.get_env("VAPID_SUBJECT") || "mailto:admin@example.com",
  public_key: System.get_env("VAPID_PUBLIC_KEY") || "BAb03820kHYuqIvtP6QuCKZRshvv_zp5eDtqkuwCUAxASBZMQbFZXzv8kjYOuLGF16A3k8qYnIN10_4asB-Aw7w",
  private_key: System.get_env("VAPID_PRIVATE_KEY") || "w76tXh1d3RBdVQ5eINevXRwW6Ow6uRcBa8tBDOXfmxM"

config :sentry,
  environment_name: :dev,
  json_library: Poison,
  included_environments: [],
  tags: %{
    env: "dev"
  }

config :ret, Ret.Habitat, ip: "127.0.0.1", http_port: 9631

config :ret, Ret.RoomAssigner, balancer_weights: [{600, 1}, {300, 50}, {0, 500}]

config :ret, RetWeb.PageController,
  skip_cache: true,
  assets_path: "storage/assets",
  docs_path: "storage/docs"

config :ret, Ret.HttpUtils, insecure_ssl: true

config :ret, Ret.Meta, phx_host: host

config :ret, Ret.Locking, lock_timeout_ms: 1000 * 60 * 15

# Dialog certificate paths (single source of truth for service auth)
# The Dockerfile copies these certs at build time to the container paths below.
config :ret, :dialog,
  auth_key_path: "/etc/perms.pub.pem",
  cert_fullchain_path: "/etc/ssl/fullchain.pem",
  cert_privkey_path: "/etc/ssl/privkey.pem"

config :ret, Ret.Repo.Migrations.AdminSchemaInit, postgrest_password: System.get_env("POSTGREST_PASSWORD") || "password"
config :ret, Ret.StatsJob, node_stats_enabled: false, node_gauges_enabled: false
config :ret, Ret.Coturn, realm: "ret"
